---
title: "Homework 7"
author: "Davit Kajaia"
date: "5/13/2020"
output: html_document
---

# Homework 7

## Libraries

```{r message=FALSE}
library(tidyverse)
library(wbstats)
library(tmap)
library(rnaturalearth)
library(dplyr)

```

## Choosing indicator

```{r}
wbstats_indicators <- wb_cachelist$indicators
write.csv(wbstats_indicators, file = "wbstats_indicators.csv")
```

After exporting indicators to CSV files I chose "Renewable electricity (% in total electricity output): Share of electrity generated by renewable power plants in total electricity" with ID - "4.1_SHARE.RE.IN.ELECTRICITY"

```{r}
data<- wb(indicator ="4.1_SHARE.RE.IN.ELECTRICITY",
                   mrv = 1, return_wide = TRUE)
glimpse(data)
colnames(data)[5]<-"Value"
glimpse(data)
```

## Downloading map


```{r}
countries <- ne_download(scale = 50, type = 'countries', category = 'cultural', returnclass = "sf")
countries2 <- countries %>% 
  dplyr::select(ADM0_A3, NAME, GDP_MD_EST, POP_EST)
```

## joining data table with geospatial layer

```{r}
data_joined <- left_join(countries2, data, by = c("ADM0_A3" = "iso3c"))
```

## Creating map

```{r warning=TRUE}
tmap_mode("plot")
tm_shape(data_joined)+
  tm_polygons(col = "Value", 
              style = "kmeans",
              n=5,
              palette=c('#d7191c','#fdae61','#ffffbf','#a6d96a','#1a9641'), 
              border.col = "grey50",
              lwd = 0.2,
              title = "Percentage",
              colorNA  = "grey80")+
  tm_style("natural")+
  tm_format("NLD")+
  tm_layout(main.title = "Share of Renewable Electricity",
            legend.bg.color = "white",
            legend.bg.alpha = 0.6)+
  tm_credits("Data: World Bank\nMap: D. Kajaia",
             bg.color = "white",
             bg.alpha = 0.7)
```

```{r}
tmap_mode("view")
tm_shape(data_joined)+
  tm_polygons(col = "Value", 
              style = "kmeans",
              n=5,
              palette=c('#d7191c','#fdae61','#ffffbf','#a6d96a','#1a9641'), 
              border.col = "grey50",
              lwd = 0.2,
              title = "Percentage",
              colorNA  = "grey80")+
  tm_style("natural")+
  tm_format("NLD")+
  tm_layout(main.title = "Share of Renewable Electricity",
            legend.bg.color = "white",
            legend.bg.alpha = 0.6)+
  tm_credits("Data: World Bank\nMap: D. Kajaia",
             bg.color = "white",
             bg.alpha = 0.7)
```

